// Generated by papersmith — do not edit by hand.
//
// Native Pi relay for the workspace "refuse off-path push" tripwire.
//
// Pi loads project extensions from `.pi/extensions/` (TypeScript or JavaScript
// files with a default factory taking `ExtensionAPI`) and lets a `tool_call`
// handler return `{ block: true, reason }`:
// https://github.com/badlogic/pi-mono/blob/main/packages/coding-agent/docs/extensions.md
// The bash input field name (`event.input.command`) follows the upstream
// `permission-gate.ts` example extension.
//
// This file deliberately does NOT re-implement the predicate. It shells out to
// the Python guard that ships with the remote-execution skill, so there is
// exactly one authority for the rule, and a second service is covered by that
// service's own adapter declaring its own PUSH_SURFACE — never by editing here.
//
// Honest bound: the Python side is a tripwire, not a gate. This relay inherits
// that bound unchanged. It never claims more than the hook it delegates to.
//
// Fail-open on purpose: Pi blocks a tool call when a `tool_call` handler THROWS
// (documented fail-safe), so every path here is wrapped and a missing guard,
// missing python, spawn error, timeout or malformed event allows the call after
// one warning. Only an explicit exit status 2 from the guard blocks.

import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HOOK_RELATIVE = "skills/remote-execution/scripts/hooks/refuse_offpath_push.py";
const ADAPTERS_RELATIVE = "skills/remote-execution/scripts/adapters";
const TIMEOUT_MS = 5000;

// One-time capability probe. It loads the hook by path and calls the hook's own
// `_load_push_surfaces()`, then compares that loaded set against every
// PUSH_SURFACE literal ast-parsed from the adapters, so an inert hook is never
// mistaken for a clean allow.
const PROBE_SOURCE = `
import ast, importlib.util, json, pathlib, sys

root = pathlib.Path(sys.argv[1])
hook_path = root / "skills/remote-execution/scripts/hooks/refuse_offpath_push.py"
adapters_dir = root / "skills/remote-execution/scripts/adapters"

state = {"ok": False, "reason": ""}


def emit(reason):
    state["reason"] = reason
    print(json.dumps(state))
    raise SystemExit(0)


if not hook_path.is_file():
    emit("hook not found")
if not adapters_dir.is_dir():
    emit("adapters directory not found")

spec = importlib.util.spec_from_file_location("_refuse_offpath_probe", hook_path)
if spec is None or spec.loader is None:
    emit("hook could not be loaded")
module = importlib.util.module_from_spec(spec)
try:
    spec.loader.exec_module(module)
except Exception as exc:
    emit("hook import failed: " + str(exc))

loader = getattr(module, "_load_push_surfaces", None)
if not callable(loader):
    emit("hook exposes no _load_push_surfaces()")
try:
    loaded = {str(token) for token in loader(adapters_dir)}
except Exception as exc:
    emit("_load_push_surfaces() failed: " + str(exc))

declared = set()
for path in sorted(adapters_dir.glob("*.py")):
    if path.name == "__init__.py":
        continue
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except Exception:
        continue
    for node in tree.body:
        target, value = None, None
        if isinstance(node, ast.Assign):
            names = [t for t in node.targets if isinstance(t, ast.Name)]
            if names:
                target, value = names[0].id, node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            target, value = node.target.id, node.value
        if target != "PUSH_SURFACE" or value is None:
            continue
        try:
            literal = ast.literal_eval(value)
        except Exception:
            emit("PUSH_SURFACE in " + path.name + " is not a literal")
        for token in literal:
            declared.add(str(token))

missing = sorted(declared - loaded)
if missing:
    emit("declared push surfaces not loaded: " + ", ".join(missing))
state["ok"] = True
print(json.dumps(state))
`;

function projectRoot() {
  // This file lives at <root>/.pi/extensions/refuse-offpath-push.js. Anchor on
  // the file, never on the process cwd.
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
}

function interpreterCandidates(root) {
  const candidates = [];
  if (process.env.VIRTUAL_ENV) {
    candidates.push(path.join(process.env.VIRTUAL_ENV, "bin", "python"));
  }
  candidates.push(path.join(root, ".venv", "bin", "python"));
  candidates.push("python3");
  return candidates;
}

function run(interpreter, args, cwd, input) {
  return spawnSync(interpreter, args, {
    cwd,
    input,
    encoding: "utf8",
    timeout: TIMEOUT_MS,
    env: Object.assign({}, process.env),
  });
}

function probe(root) {
  const missing = [];
  for (const relative of [HOOK_RELATIVE, ADAPTERS_RELATIVE]) {
    if (!existsSync(path.join(root, relative))) {
      missing.push(relative);
    }
  }
  if (missing.length) {
    return { ok: false, reason: "not found: " + missing.join(", ") };
  }
  for (const interpreter of interpreterCandidates(root)) {
    const result = run(interpreter, ["-c", PROBE_SOURCE, root], root, null);
    if (result.error && result.error.code === "ENOENT") {
      continue;
    }
    if (result.error || result.signal) {
      continue;
    }
    if (result.status !== 0) {
      continue;
    }
    try {
      const parsed = JSON.parse(String(result.stdout).trim());
      return { ok: Boolean(parsed.ok), reason: String(parsed.reason || "") };
    } catch (error) {
      return { ok: false, reason: "probe produced unreadable output" };
    }
  }
  return { ok: false, reason: "no usable python interpreter for the capability probe" };
}

function classify(root, command) {
  const hook = path.join(root, HOOK_RELATIVE);
  if (!existsSync(hook)) {
    return { kind: "degraded", reason: "hook not found at " + HOOK_RELATIVE };
  }
  const payload = JSON.stringify({ tool_name: "Bash", tool_input: { command } });
  for (const interpreter of interpreterCandidates(root)) {
    const result = run(interpreter, [hook], root, payload);
    if (result.error && result.error.code === "ENOENT") {
      continue;
    }
    if (result.error) {
      return { kind: "degraded", reason: result.error.message };
    }
    if (result.signal) {
      return { kind: "degraded", reason: "hook killed by " + result.signal };
    }
    if (result.status === 0) {
      return { kind: "allow" };
    }
    if (result.status === 2) {
      return { kind: "refuse", detail: String(result.stderr || "").trim() };
    }
    return { kind: "degraded", reason: "hook exited " + result.status };
  }
  return { kind: "degraded", reason: "no usable python interpreter" };
}

export default function (pi) {
  let warningIssued = false;
  let capability = null;

  const degrade = (reason) => {
    // One warning per process: silent fail-open is forbidden, repeated noise is not wanted.
    if (warningIssued) {
      return;
    }
    warningIssued = true;
    console.error("[refuse-offpath-push] degraded: " + reason + " — allowing the command.");
  };

  const decide = (event) => {
    if (!event || event.toolName !== "bash") {
      return undefined;
    }
    const command = event.input ? event.input.command : undefined;
    if (typeof command !== "string" || !command) {
      return undefined;
    }
    const root = projectRoot();
    // The hook is inert without a complete surface set, so prove the set loads
    // before trusting an allow. A degraded probe warns once and then allows.
    if (capability === null) {
      capability = probe(root);
      if (!capability.ok) {
        degrade(capability.reason);
      }
    }
    if (!capability.ok) {
      return undefined;
    }
    const decision = classify(root, command);
    if (decision.kind === "degraded") {
      degrade(decision.reason);
      return undefined;
    }
    if (decision.kind === "refuse") {
      return {
        block: true,
        reason:
          "refuse-offpath-push: " +
          (decision.detail || "this command names a push surface without invoking remote_cli.py"),
      };
    }
    return undefined;
  };

  pi.on("tool_call", async (event) => {
    try {
      return decide(event);
    } catch (error) {
      // A throwing handler would block the tool call in Pi; this guard never does.
      degrade(error && error.message ? error.message : String(error));
      return undefined;
    }
  });
}
