# {{title}} — Pi Entrypoint

This Pi workspace is a deterministic projection of the `.claude/` SSOT,
generated by `papersmith` {{version}}.

Read `papersmith.yaml`, `guidance/paper-guide/`, and the applicable
`skills/*/SKILL.md` before working on the paper.

## Agents

{{agents}}

## Commands

Pi receives no generated slash commands — only the `claude` and `opencode`
projections emit command files. Invoke a capability by name; read the applicable
`skills/<name>/SKILL.md` first, since that file remains the source of truth.
