// Generated by papersmith — do not edit by hand.
//
// Native Pi relay for the workspace "refuse off-path push" tripwire.
//
// This file deliberately does NOT re-implement the predicate. It shells out to
// the Python guard that ships with the remote-execution skill, so there is
// exactly one authority for the rule, and a second service is covered by that
// service's own adapter declaring its own PUSH_SURFACE — never by editing here.
//
// Honest bound: the Python side is a tripwire, not a gate. This relay inherits
// that bound unchanged. It never claims more than the hook it delegates to.
//
// Pi contract this file depends on: a failing `tool_call` handler blocks the
// tool as a fail-safe ("Errors and cleanup" in Pi's docs/extensions.md), so
// every path here RETURNS a result and none of them throws — including while
// degrading. The entry point must be the default export:
// `jiti.import(path, { default: true })` returns it, and a module that is not a
// function makes Pi reject the file and take every `pi` command down with it.
// A generated workspace does not install the Pi runtime, so the structural types
// this file needs are declared locally and nothing is imported from
// "@earendil-works/pi-coding-agent".

import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";

interface ToolCallEvent {
  toolName?: string;
  input?: { command?: unknown };
}

interface ExtensionContext {
  cwd?: string;
  hasUI?: boolean;
}

interface ToolCallEventResult {
  block?: boolean;
  reason?: string;
}

interface ExtensionApi {
  on(
    event: "tool_call",
    handler: (event: ToolCallEvent, ctx: ExtensionContext) => Promise<ToolCallEventResult | undefined>,
  ): unknown;
}

type Capability = { ok: boolean; reason: string };

type Decision =
  | { kind: "allow" }
  | { kind: "refuse"; detail: string }
  | { kind: "degraded"; reason: string };

const HOOK_RELATIVE = "skills/remote-execution/scripts/hooks/refuse_offpath_push.py";
const ADAPTERS_RELATIVE = "skills/remote-execution/scripts/adapters";
const TIMEOUT_MS = 5000;

// One-time capability probe. It loads the hook by path and calls the hook's own
// `_load_push_surfaces()`, then compares that loaded set against every
// PUSH_SURFACE literal ast-parsed from the adapters. The hook exposes NO
// module-level PUSH_SURFACE (the tokens live in the adapters), so reading an
// attribute off the hook module would find nothing and false-degrade.
const PROBE_SOURCE = `
import ast, importlib.util, json, pathlib, sys

root = pathlib.Path(sys.argv[1])
hook_path = root / "skills/remote-execution/scripts/hooks/refuse_offpath_push.py"
adapters_dir = root / "skills/remote-execution/scripts/adapters"

state = {"ok": False, "reason": ""}


def emit(reason):
    state["reason"] = reason
    print(json.dumps(state))
    raise SystemExit(0)


if not hook_path.is_file():
    emit("hook not found")
if not adapters_dir.is_dir():
    emit("adapters directory not found")

spec = importlib.util.spec_from_file_location("_refuse_offpath_probe", hook_path)
if spec is None or spec.loader is None:
    emit("hook could not be loaded")
module = importlib.util.module_from_spec(spec)
try:
    spec.loader.exec_module(module)
except Exception as exc:
    emit("hook import failed: " + str(exc))

loader = getattr(module, "_load_push_surfaces", None)
if not callable(loader):
    emit("hook exposes no _load_push_surfaces()")
try:
    loaded = {str(token) for token in loader(adapters_dir)}
except Exception as exc:
    emit("_load_push_surfaces() failed: " + str(exc))

declared = set()
for path in sorted(adapters_dir.glob("*.py")):
    if path.name == "__init__.py":
        continue
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except Exception:
        continue
    for node in tree.body:
        target, value = None, None
        if isinstance(node, ast.Assign):
            names = [t for t in node.targets if isinstance(t, ast.Name)]
            if names:
                target, value = names[0].id, node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            target, value = node.target.id, node.value
        if target != "PUSH_SURFACE" or value is None:
            continue
        try:
            literal = ast.literal_eval(value)
        except Exception:
            emit("PUSH_SURFACE in " + path.name + " is not a literal")
        for token in literal:
            declared.add(str(token))

missing = sorted(declared - loaded)
if missing:
    emit("declared push surfaces not loaded: " + ", ".join(missing))
state["ok"] = True
print(json.dumps(state))
`;

function interpreterCandidates(root: string): string[] {
  const candidates: string[] = [];
  if (process.env.VIRTUAL_ENV) {
    candidates.push(path.join(process.env.VIRTUAL_ENV, "bin", "python"));
  }
  candidates.push(path.join(root, ".venv", "bin", "python"));
  candidates.push("python3");
  return candidates;
}

function run(interpreter: string, args: string[], cwd: string, input: string | null) {
  return spawnSync(interpreter, args, {
    cwd,
    input: input === null ? undefined : input,
    encoding: "utf8",
    timeout: TIMEOUT_MS,
    env: Object.assign({}, process.env),
  });
}

// Pi's ExtensionContext exposes `cwd` and nothing like a project root, so the
// workspace root is the nearest ancestor of `ctx.cwd` that carries the hook.
// `null` means the hook is not on this path at all.
function resolveRoot(start: string): string | null {
  let current = path.resolve(start);
  for (;;) {
    if (existsSync(path.join(current, HOOK_RELATIVE))) {
      return current;
    }
    const parent = path.dirname(current);
    if (parent === current) {
      return null;
    }
    current = parent;
  }
}

function probe(root: string): Capability {
  const missing: string[] = [];
  for (const relative of [HOOK_RELATIVE, ADAPTERS_RELATIVE]) {
    if (!existsSync(path.join(root, relative))) {
      missing.push(relative);
    }
  }
  if (missing.length) {
    return { ok: false, reason: "not found: " + missing.join(", ") };
  }
  for (const interpreter of interpreterCandidates(root)) {
    const result = run(interpreter, ["-c", PROBE_SOURCE, root], root, null);
    if (result.error && (result.error as NodeJS.ErrnoException).code === "ENOENT") {
      continue;
    }
    if (result.error || result.signal) {
      continue;
    }
    if (result.status !== 0) {
      continue;
    }
    try {
      const parsed = JSON.parse(String(result.stdout).trim());
      return { ok: Boolean(parsed.ok), reason: String(parsed.reason || "") };
    } catch (error) {
      return { ok: false, reason: "probe produced unreadable output" };
    }
  }
  return { ok: false, reason: "no usable python interpreter for the capability probe" };
}

function classify(root: string, command: string): Decision {
  const hook = path.join(root, HOOK_RELATIVE);
  if (!existsSync(hook)) {
    return { kind: "degraded", reason: "hook not found at " + HOOK_RELATIVE };
  }
  const payload = JSON.stringify({ tool_name: "Bash", tool_input: { command } });
  for (const interpreter of interpreterCandidates(root)) {
    const result = run(interpreter, [hook], root, payload);
    if (result.error && (result.error as NodeJS.ErrnoException).code === "ENOENT") {
      continue;
    }
    if (result.error) {
      return { kind: "degraded", reason: result.error.message };
    }
    if (result.signal) {
      return { kind: "degraded", reason: "hook killed by " + result.signal };
    }
    if (result.status === 0) {
      return { kind: "allow" };
    }
    if (result.status === 2) {
      return { kind: "refuse", detail: String(result.stderr || "").trim() };
    }
    return { kind: "degraded", reason: "hook exited " + result.status };
  }
  return { kind: "degraded", reason: "no usable python interpreter" };
}

export default function refuseOffpathPush(pi: ExtensionApi): void {
  let warningIssued = false;
  const capabilities = new Map<string, Capability>();

  const degrade = (reason: string): void => {
    // One warning per process: silent fail-open is forbidden, repeated noise is not wanted.
    if (warningIssued) {
      return;
    }
    warningIssued = true;
    try {
      console.error("[refuse-offpath-push] degraded: " + reason + " — allowing the command.");
    } catch (error) {
      // A console that cannot report is still not a reason to block: this
      // handler failing is what Pi turns into a fail-safe block.
    }
  };

  const capabilityOk = (root: string): boolean => {
    let capability = capabilities.get(root);
    if (!capability) {
      capability = probe(root);
      capabilities.set(root, capability);
    }
    if (!capability.ok) {
      degrade(capability.reason);
    }
    return capability.ok;
  };

  pi.on("tool_call", async (event, ctx) => {
    // The whole body is wrapped, not just the guard call: an unexpected throw
    // out of a `tool_call` handler blocks the tool as a fail-safe, so every
    // failure path here degrades loudly and then ALLOWS.
    try {
      if (!event || event.toolName !== "bash") {
        return undefined;
      }
      const command = event.input ? event.input.command : undefined;
      if (typeof command !== "string" || !command) {
        return undefined;
      }
      const cwd = ctx && typeof ctx.cwd === "string" && ctx.cwd ? ctx.cwd : process.cwd();
      const root = resolveRoot(cwd);
      if (!root) {
        degrade("hook not found from " + cwd);
        return undefined;
      }
      // The hook is inert without a complete surface set, so prove the set loads
      // before trusting an allow. A degraded probe warns once and then allows.
      if (!capabilityOk(root)) {
        return undefined;
      }
      const decision = classify(root, command);
      if (decision.kind === "degraded") {
        degrade(decision.reason);
        return undefined;
      }
      if (decision.kind === "refuse") {
        // Blocking is a RETURNED result in Pi, never a throw.
        return {
          block: true,
          reason: "refuse-offpath-push: " +
            (decision.detail || "this command names a push surface without invoking remote_cli.py"),
        };
      }
      return undefined;
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      degrade("unexpected failure: " + detail);
      return undefined;
    }
  });
}
