import { ENGINE_MODULE_ROOT } from './_engine-module-root.mjs';
import assert from 'node:assert/strict'; import { createHash } from 'node:crypto'; import { mkdtemp,mkdir,readFile } from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path'; import test from 'node:test'; import { pathToFileURL } from 'node:url';
const piRoot=ENGINE_MODULE_ROOT;const {createJiti}=await import(pathToFileURL(path.join(piRoot,'node_modules/jiti/lib/jiti.mjs')).href);const jiti=createJiti(import.meta.url,{alias:{'@earendil-works/pi-coding-agent':path.join(piRoot,'dist/index.js'),'@earendil-works/pi-ai/compat':path.join(piRoot,'node_modules/@earendil-works/pi-ai/dist/compat.js'),'@earendil-works/pi-ai':path.join(piRoot,'node_modules/@earendil-works/pi-ai/dist/index.js'),typebox:path.join(piRoot,'node_modules/typebox/build/index.mjs')}});const workspaceModule=await jiti.import(path.resolve('.claude/skills/_core/deliberation/engine/proposal-workspace.ts'));const v2=await jiti.import(path.resolve('.claude/skills/_core/deliberation/engine/exports.ts'));
const content='# Proposal\n\nOpening boundary.\n\n## Source\n\nMove this exact paragraph.\n\n### Child\n\nChild content stays attached.\n\n## Destination\n\nDestination boundary.\n\n## Other\n\nOther boundary.\n';
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'pp-v2-mc-'));await mkdir(path.join(root,'proposals'),{recursive:true});const bootstrap=workspaceModule.createProposalWorkspaceTool(root);await bootstrap.execute('seed',{action:'write',resource:'proposal',slug:'r01',content});const guard=workspaceModule.createDocumentOperationGuard(root);const workspace=workspaceModule.createProposalWorkspaceTool(root,{operationGuard:guard});return {root,adapter:new v2.ProposalWorkspaceAdapter(root,guard,workspace,()=>`move-copy-${Math.random()}`)}}
async function ids(root){const s=await v2.loadDocumentState(root,'research-concept-r01.md');const find=(value,type)=>s.structuralIndex.entries.find(e=>(!type||e.type===type)&&s.documentBytes.subarray(e.startByte,e.endByte).toString().includes(value)).entryId;return {paragraph:find('Move this exact','paragraph'),source:find('## Source','subsection'),child:find('### Child','heading'),destination:find('## Destination','subsection'),other:find('## Other','subsection')}}
test('MOVE literal paragraph publishes one immutable successor',async()=>{const {root,adapter}=await fixture();const i=await ids(root);const result=await new v2.ProposalDeliberationOrchestrator(root,adapter).execute({instruction:'mueve literal',sourceQuery:i.paragraph,destinationQuery:i.destination,position:'inside_end'});assert.equal(result.status,'published');assert.equal(result.modelCalls,0);assert.equal(result.plannerCalls,0);const r01=await readFile(path.join(root,'proposals/research-concept-r01.md'));const r02=await readFile(path.join(root,'proposals/research-concept-r02.md'),'utf8');assert.equal((r02.match(/Move this exact paragraph\./g)??[]).length,1);assert.match(r02,/## Destination[\s\S]*Move this exact paragraph/);assert.equal(r01.toString().includes('Move this exact paragraph.'),true);assert.equal(result.published.publishedSha256,createHash('sha256').update(await readFile(path.join(root,'proposals/research-concept-r02.md'))).digest('hex'));assert.equal(result.derived.derivedStateManifest.status,'COMMITTED');assert.equal(result.receipt.targetFilename,'research-concept-r02.md');assert.equal((await new v2.ProposalDeliberationOrchestrator(root,adapter).latest()),'research-concept-r02.md')});
test('COPY literal preserves source and adds exactly one copy',async()=>{const {root,adapter}=await fixture();const i=await ids(root);const result=await new v2.ProposalDeliberationOrchestrator(root,adapter).execute({instruction:'copia literal',sourceQuery:i.paragraph,destinationQuery:i.destination,position:'inside_end'});assert.equal(result.status,'published');assert.equal(result.plannerCalls,0);const r02=await readFile(path.join(root,'proposals/research-concept-r02.md'),'utf8');assert.equal((r02.match(/Move this exact paragraph\./g)??[]).length,2)});
test('MOVE literal section retains child subtree',async()=>{const {root,adapter}=await fixture();const i=await ids(root);const result=await new v2.ProposalDeliberationOrchestrator(root,adapter).execute({instruction:'mueve sección',sourceQuery:i.source,destinationQuery:i.other,position:'inside_end'});assert.equal(result.status,'published');const r02=await readFile(path.join(root,'proposals/research-concept-r02.md'),'utf8');assert.match(r02,/## Other[\s\S]*## Source[\s\S]*### Child[\s\S]*Child content stays attached/) });
test('MOVE adaptive invokes exactly one planner',async()=>{const {root,adapter}=await fixture();const i=await ids(root);let calls=0;const planner={plan:async()=>{calls++;return {transformedContent:'Adapted moved paragraph.'}}};const result=await new v2.ProposalDeliberationOrchestrator(root,adapter,undefined,planner).execute({instruction:'mueve y adapta la transición',sourceQuery:i.paragraph,destinationQuery:i.destination,position:'inside_end'});assert.equal(result.status,'published');assert.equal(calls,1);assert.equal(result.plannerCalls,1)});
test('COPY adaptive invokes exactly one planner',async()=>{const {root,adapter}=await fixture();const i=await ids(root);let calls=0;const planner={plan:async()=>{calls++;return {transformedContent:'Adapted copied paragraph.'}}};const result=await new v2.ProposalDeliberationOrchestrator(root,adapter,undefined,planner).execute({instruction:'copia y ajusta al nuevo contexto',sourceQuery:i.paragraph,destinationQuery:i.destination,position:'inside_end'});assert.equal(result.status,'published');assert.equal(calls,1);assert.equal(result.plannerCalls,1)});
test('ambiguous source and destination never publish',async()=>{const {root,adapter}=await fixture();const i=await ids(root);const o=new v2.ProposalDeliberationOrchestrator(root,adapter);assert.equal((await o.execute({instruction:'mueve',sourceQuery:'boundary',destinationQuery:i.destination})).status,'ambiguous');assert.equal((await o.execute({instruction:'copia',sourceQuery:i.paragraph,destinationQuery:'boundary'})).status,'ambiguous')});
test('missing source and destination never publish',async()=>{const {root,adapter}=await fixture();const i=await ids(root);const o=new v2.ProposalDeliberationOrchestrator(root,adapter);assert.equal((await o.execute({instruction:'mueve',sourceQuery:'not present',destinationQuery:i.destination})).status,'ambiguous');assert.equal((await o.execute({instruction:'copia',sourceQuery:i.paragraph,destinationQuery:'not present'})).status,'ambiguous')});
test('blocks section within itself and parent into descendant',async()=>{const {root,adapter}=await fixture();const i=await ids(root);const o=new v2.ProposalDeliberationOrchestrator(root,adapter);assert.equal((await o.execute({instruction:'mueve',sourceQuery:i.source,destinationQuery:i.source})).status,'blocked');assert.equal((await o.execute({instruction:'mueve',sourceQuery:i.source,destinationQuery:i.child})).status,'blocked')});
test('planner unresolved questions do not publish',async()=>{const {root,adapter}=await fixture();const i=await ids(root);const result=await new v2.ProposalDeliberationOrchestrator(root,adapter,undefined,{plan:async()=>({unresolvedQuestions:['Which transition?']})}).execute({instruction:'mueve y reformula para que encaje',sourceQuery:i.paragraph,destinationQuery:i.destination});assert.equal(result.status,'needs-clarification');assert.equal(result.mutations,0)});
test('planner cannot invent identifiers, move destination, or create two actions',async()=>{for(const proposal of [{transformedContent:'x',sourceEntryIds:['invented']},{transformedContent:'x',destinationEntryId:'invented'},{transformedContent:'x',actions:[{},{}]}]){const {root,adapter}=await fixture();const i=await ids(root);const result=await new v2.ProposalDeliberationOrchestrator(root,adapter,undefined,{plan:async()=>proposal}).execute({instruction:'mueve y adapta la transición',sourceQuery:i.paragraph,destinationQuery:i.destination});assert.equal(result.status,'blocked')}});
