"""From-scratch command series: every ``papersmith`` command over a CLI-made workspace.

Layer purpose. The paper journey (``test_cli_paper_e2e.py``) walks the research
flow once; this module proves the other half of the product claim: that a
workspace generated by ``papersmith init`` is a working instrument for *every*
command the CLI advertises, including the ones the journey never touches
(``upgrade``, ``target``). Deep engine legs stay in their own suites; every
test here starts from ``init`` and drives the CLI as a user would.

Boundaries stay hermetic: stubbed ingest, symlinked ``node_modules``, dry-run
dispatch, no network, no model calls, no live Kaggle.
"""

from __future__ import annotations

import ast
import contextlib
import io
import json
import os
import shutil
import signal
import stat as stat_module
import subprocess
import unittest
import warnings as _warnings
from pathlib import Path
from unittest import mock

from papersmith.bridges import audit as audit_module
from papersmith.cli import main
from papersmith.core import ledger as run_ledger
from papersmith.core import manifest as manifest_module
from papersmith.core import status as status_module
from papersmith.core import upgrade as upgrade_module
from papersmith.core.exit_codes import DRIFT_ERROR, SUCCESS, USER_ERROR
from papersmith.errors import UserError
from papersmith.kit import resolve_and_validate

from workspace_series import (
    FIXTURE_PDF,
    REPO_ROOT,
    capture,
    link_node_modules,
    make_demo_target,
    make_workspace,
    new_tmp,
    stub_extract,
)

COMMANDS = (
    "init",
    "upgrade",
    "status",
    "ingest",
    "deliberate",
    "implement",
    "run",
    "remote",
    "target",
    "audit",
)


def _help_door(command: str):
    """Run ``<command> --help`` and return ``(exit code, printed help)``."""
    buffer = io.StringIO()
    try:
        with contextlib.redirect_stdout(buffer):
            main([command, "--help"])
    except SystemExit as exc:
        return exc.code, buffer.getvalue()
    raise AssertionError(f"{command} --help did not exit through SystemExit")


class CommandRosterTests(unittest.TestCase):
    """Every advertised command answers its own front door."""

    def test_every_command_has_a_working_help_door(self) -> None:
        for command in COMMANDS:
            with self.subTest(command=command):
                code, text = _help_door(command)
                self.assertEqual(code, 0, f"{command} --help must exit 0")
                self.assertIn("usage:", text, f"{command} printed no usage")

    def test_version_is_a_top_level_flag(self) -> None:
        buffer = io.StringIO()
        with contextlib.redirect_stdout(buffer):
            with self.assertRaises(SystemExit) as caught:
                main(["--version"])
        self.assertEqual(caught.exception.code, 0)
        self.assertIn("papersmith", buffer.getvalue())


class GeneratedWorkspaceTests(unittest.TestCase):
    """``init`` from the CLI is the only generator used by this series."""

    def test_init_creates_a_ready_workspace(self) -> None:
        workspace = make_workspace(new_tmp(self))
        for relpath in (
            ".papersmith/manifest.json",
            ".papersmith/config.json",
            ".papersmith/version",
            "papersmith.yaml",
            "CLAUDE.md",
            "OPENCODE.md",
            "PI.md",
            ".pi/gentle-ai/persona.json",
            ".antigravity/rules.md",
            "README.md",
            "package.json",
            ".mcp.json",
            "skills/paper-writing/SKILL.md",
            "skills/proposal-deliberation/cli.mjs",
            "scripts/setup_env.py",
            "scripts/setup-harnesses.sh",
        ):
            self.assertTrue((workspace / relpath).exists(), relpath)
        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        payload = json.loads(out)
        self.assertEqual(payload["project_name"], "series-ws")
        self.assertEqual(payload["framework"]["drifted_files"], [])
        self.assertTrue(payload["framework"]["version_match"])

    def test_status_names_drift_without_failing(self) -> None:
        # Documented known gap: status reports drift by name and still exits 0.
        workspace = make_workspace(new_tmp(self))
        claude = workspace / "CLAUDE.md"
        claude.write_text(claude.read_text(encoding="utf-8") + "\n<!-- probe -->\n",
                          encoding="utf-8")
        rc, out, _ = capture(["status", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("CLAUDE.md", out)


class UpgradeCommandTests(unittest.TestCase):

    def test_upgrade_restores_framework_files_and_preserves_research(self) -> None:
        workspace = make_workspace(new_tmp(self))
        skill = workspace / "skills/paper-ingestion/SKILL.md"
        original = skill.read_bytes()
        skill.write_bytes(b"tampered by the test\n")
        research = workspace / "guidance/paper-guide/notes.md"
        research.write_text("research stays\n", encoding="utf-8")
        rc, out, _ = capture(["upgrade", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("Upgraded papersmith workspace", out)
        self.assertEqual(skill.read_bytes(), original, "upgrade must restore framework bytes")
        self.assertEqual(research.read_text(encoding="utf-8"), "research stays\n")
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("drift: clean", out)


class HarnessProjectionTests(unittest.TestCase):
    """The workspace ships the script its package.json advertises for harness wiring."""

    HARNESS_LINKS = (".claude/skills", ".pi/skills", ".opencode/skills", ".antigravity/skills")

    def test_projection_script_wires_every_harness(self) -> None:
        workspace = make_workspace(new_tmp(self))
        package = (workspace / "package.json").read_text(encoding="utf-8")
        self.assertIn("bash scripts/setup-harnesses.sh", package)
        script = workspace / "scripts" / "setup-harnesses.sh"
        self.assertTrue(script.is_file(), "the workspace must ship the script it advertises")

        first = subprocess.run(
            ["bash", str(script)], cwd=workspace, capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(first.returncode, 0, first.stderr)
        for relpath in self.HARNESS_LINKS:
            link = workspace / relpath
            self.assertTrue(link.is_symlink(), f"{relpath} must be a symlink")
            self.assertEqual(os.readlink(link), os.path.relpath(workspace / "skills", link.parent))
            self.assertTrue((link / "paper-ingestion" / "SKILL.md").is_file(), relpath)

        second = subprocess.run(
            ["bash", str(script)], cwd=workspace, capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(second.returncode, 0, second.stderr)
        for relpath in self.HARNESS_LINKS:
            self.assertTrue((workspace / relpath).is_symlink(), f"{relpath} must survive a re-run")


class HarnessCommandProjectionTests(unittest.TestCase):
    """The nine skills arrive as slash commands, plus the OpenCode safety plugin."""

    COMMAND_NAMES = (
        "experimental-deliberation",
        "experimental-implementation",
        "kaggle-accounts",
        "paper-ingestion",
        "paper-writing",
        "proposal-deliberation",
        "proposal-implementation",
        "remote-execution",
        "skill-audit",
    )

    def test_init_projects_nine_commands_per_command_harness(self) -> None:
        workspace = make_workspace(new_tmp(self))
        for harness in (".opencode/commands", ".claude/commands"):
            with self.subTest(harness=harness):
                names = sorted(path.stem for path in (workspace / harness).glob("*.md"))
                self.assertEqual(names, sorted(self.COMMAND_NAMES))
                body = (workspace / harness / "paper-ingestion.md").read_text(encoding="utf-8")
                self.assertIn("$ARGUMENTS", body)
                self.assertIn("skills/paper-ingestion/SKILL.md", body)

    def test_non_command_harnesses_receive_no_command_directory(self) -> None:
        workspace = make_workspace(new_tmp(self))
        self.assertFalse((workspace / ".pi/commands").exists())
        self.assertFalse((workspace / ".antigravity/commands").exists())

    def test_opencode_json_is_valid_and_declares_no_plugin_key(self) -> None:
        workspace = make_workspace(new_tmp(self))
        payload = json.loads((workspace / "opencode.json").read_text(encoding="utf-8"))
        self.assertEqual(payload["$schema"], "https://opencode.ai/config.json")
        self.assertIn("permission", payload)
        self.assertNotIn("plugin", payload,
                         "plugins are auto-discovered; a plugin key would duplicate that")

    def test_opencode_plugin_is_the_generated_relay(self) -> None:
        workspace = make_workspace(new_tmp(self))
        text = (workspace / ".opencode/plugins/refuse-offpath-push.js").read_text(encoding="utf-8")
        self.assertIn("export const server", text)
        self.assertIn("tool.execute.before", text)
        self.assertIn("_load_push_surfaces", text)

    def test_audit_is_clean_and_upgrade_restores_a_tampered_command(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("drift: clean", out)

        command = workspace / ".opencode/commands/paper-writing.md"
        original = command.read_bytes()
        command.write_bytes(b"tampered\n")
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, DRIFT_ERROR)
        self.assertIn(".opencode/commands/paper-writing.md", out)
        self.assertEqual(command.read_bytes(), b"tampered\n", "audit must never repair")

        rc, _, _ = capture(["upgrade", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertEqual(command.read_bytes(), original)


class RenderedSetLifecycleTests(unittest.TestCase):
    """Change B: one resolver owns the tool set, ``render_files`` owns the paths.

    The five acceptance criteria that describe lifecycle behaviour rather than
    pure derivation live here. Their fixtures are deliberately written through
    the real CLI so the declared set, the rendered set, the detected set and the
    stored baseline are exercised end to end.
    """

    KIT_COMMAND_NAMES = HarnessCommandProjectionTests.COMMAND_NAMES
    STATIC_ENTRYPOINTS = ("OPENCODE.md", "PI.md", ".antigravity/rules.md")

    @staticmethod
    def _init_subset(base: Path, tools: str) -> Path:
        workspace = base / "subset"
        rc = main(["init", str(workspace), "--tools", tools, "--remote", "local", "--no-npm"])
        assert rc == SUCCESS, f"init failed with exit {rc}"
        return workspace

    def test_init_honours_a_subset_tool_selection(self) -> None:
        """Criterion 3: a correctly scoped workspace has no drift and no surplus."""
        workspace = self._init_subset(new_tmp(self), "claude")
        self.assertTrue((workspace / "CLAUDE.md").is_file())
        self.assertFalse((workspace / "OPENCODE.md").exists(),
                         "init must render only the tool set it stored")
        self.assertEqual(sorted(p.stem for p in (workspace / ".claude/commands").glob("*.md")),
                         sorted(self.KIT_COMMAND_NAMES))
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("drift: clean", out)

    def test_migration_keeps_static_entrypoints_and_names_them_as_surplus(self) -> None:
        """Criterion 4: pre-Change-B subset workspaces are reported, never damaged."""
        workspace = self._init_subset(new_tmp(self), "claude")
        for relpath in self.STATIC_ENTRYPOINTS:
            (workspace / relpath).write_text("pre-Change-B entrypoint\n", encoding="utf-8")

        rc, _, _ = capture(["upgrade", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        for relpath in self.STATIC_ENTRYPOINTS:
            with self.subTest(relpath=relpath):
                self.assertTrue((workspace / relpath).is_file(),
                                "static entrypoints are never deleted")

        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, DRIFT_ERROR)
        for relpath in self.STATIC_ENTRYPOINTS:
            with self.subTest(relpath=relpath):
                self.assertIn(relpath, out)

    def test_orphan_removal_is_baselined_dynamic_paths_only(self) -> None:
        """Criteria 5 and 6: the M1 case, plus its data-loss-safe boundary.

        A workspace-local, non-kit skill is removed, so its command stops being
        derivable and is cleaned up on both command harnesses. A hand-written
        command file that was never baselined survives.
        """
        workspace = make_workspace(new_tmp(self))
        ghost = workspace / "skills/zz-ghost"
        ghost.mkdir()
        (ghost / "SKILL.md").write_text(
            '---\nname: zz-ghost\ndescription: "Trigger: orphan fixture."\n---\n',
            encoding="utf-8",
        )
        rc, _, _ = capture(["upgrade", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        for harness in (".opencode/commands", ".claude/commands"):
            self.assertTrue((workspace / harness / "zz-ghost.md").is_file(), harness)

        shutil.rmtree(ghost)
        note = workspace / ".opencode/commands/user-note.md"
        note.write_text("hand written, never baselined\n", encoding="utf-8")

        result = upgrade_module.upgrade(workspace)
        for harness in (".opencode/commands", ".claude/commands"):
            with self.subTest(harness=harness):
                orphan = f"{harness}/zz-ghost.md"
                self.assertIn(orphan, result["removed"])
                self.assertFalse((workspace / orphan).exists())
                survivors = sorted(p.stem for p in (workspace / harness).glob("*.md"))
                self.assertTrue(set(self.KIT_COMMAND_NAMES) <= set(survivors))
        self.assertTrue(note.is_file(), "a never-baselined command file is user data")

    def test_command_drift_is_visible_to_audit_and_status_then_restored(self) -> None:
        """Criterion 7: the CA-2 reconciliation, detection and restoration agreeing."""
        workspace = make_workspace(new_tmp(self))
        command = workspace / ".opencode/commands/paper-writing.md"
        original = command.read_bytes()
        command.write_bytes(b"tampered\n")

        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, DRIFT_ERROR)
        self.assertIn(".opencode/commands/paper-writing.md", out)

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        drifted = json.loads(out)["framework"]["drifted_files"]
        self.assertIn(".opencode/commands/paper-writing.md", drifted)

        rc, _, _ = capture(["upgrade", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertEqual(command.read_bytes(), original)

    def test_malformed_skill_never_raises_from_derivation(self) -> None:
        """Criterion 8(a): a user's broken skill is reported, never fatal."""
        workspace = make_workspace(new_tmp(self))
        broken = workspace / "skills/broken"
        broken.mkdir()
        (broken / "SKILL.md").write_text("# no front matter at all\n", encoding="utf-8")

        rc, _, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        rc, _, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, SUCCESS)

    def test_workspace_operations_still_require_a_config(self) -> None:
        """Criterion 8(b): the resolver's fallback does not extend to these two.

        The workspace keeps its skill-audit probe so ``audit`` reaches the config
        read rather than failing earlier for a missing probe.
        """
        workspace = make_workspace(new_tmp(self))
        (workspace / ".papersmith/config.json").unlink()
        with self.assertRaises(UserError):
            status_module.status(workspace)
        with self.assertRaises(UserError):
            audit_module.execute(workspace, check_drift=True)

    def test_unreadable_user_files_never_break_derivation(self) -> None:
        """The M2 boundary: a damaged user file is reported, never fatal.

        ``workspace_framework_files`` derives through ``render_files``, which
        reads agent and skill front matter. Neither read may raise, or ``status``
        would abort with an untyped traceback on a workspace the previous
        implementation reported fine. An uncaught ``UnicodeDecodeError`` escapes
        ``main`` and fails here by erroring outright.
        """
        workspace = make_workspace(new_tmp(self))
        (workspace / ".claude/agents/binary.md").write_bytes(b"\xff\xfe\x00 not utf-8")
        broken = workspace / "skills/binary-skill"
        broken.mkdir()
        (broken / "SKILL.md").write_bytes(b"\xff\xfe not utf-8 either")

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        json.loads(out)
        rc, _, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertIn(rc, (SUCCESS, DRIFT_ERROR),
                      "the derivation reports; it never raises")

    def test_unsearchable_skill_directory_never_breaks_derivation(self) -> None:
        """``Path.is_file`` re-raises EACCES, so the stat calls are guarded too.

        A skill directory the user cannot traverse must not make ``status`` abort;
        the guard has to cover the stats, not only the reads.
        """
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            self.skipTest("root ignores directory permission bits")
        workspace = make_workspace(new_tmp(self))
        locked = workspace / "skills/locked"
        locked.mkdir()
        (locked / "SKILL.md").write_text(
            '---\nname: locked\ndescription: "Trigger: locked fixture."\n---\n',
            encoding="utf-8",
        )
        os.chmod(locked, 0o000)
        self.addCleanup(os.chmod, locked, 0o755)

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        json.loads(out)
        rc, _, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertIn(rc, (SUCCESS, DRIFT_ERROR), "the derivation reports; it never raises")

    def test_crafted_manifest_keys_are_refused_not_resolved(self) -> None:
        """A stored key must be a plain relative path, and containment is lexical.

        Without the lexical gate a crafted key such as
        ``.opencode/commands/../../papersmith.yaml`` stays inside the workspace
        and is still deleted. Without the guarded resolve, a non-encodable key
        aborts ``upgrade`` with an untyped exception.
        """
        workspace = make_workspace(new_tmp(self))
        guard = workspace / "papersmith.yaml"
        original = guard.read_bytes()

        manifest_path = workspace / ".papersmith" / "manifest.json"
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        traversal = ".opencode/commands/../../papersmith.yaml"
        payload["files"][traversal] = "0" * 64
        payload["files"][".opencode/commands/\x00nul.md"] = "0" * 64
        manifest_path.write_text(json.dumps(payload), encoding="utf-8")

        result = upgrade_module.upgrade(workspace)
        self.assertEqual(guard.read_bytes(), original, "no in-workspace data loss")
        self.assertNotIn(traversal, result["removed"])
        self.assertNotIn(".opencode/commands/\x00nul.md", result["removed"])

    def test_a_fifo_at_a_managed_path_never_blocks_derivation(self) -> None:
        """A non-regular managed path is skipped, not opened.

        ``open(2)`` on a FIFO with no writer blocks forever, so a guarded *read*
        is not enough: the regular-file gate has to come first. The alarm turns a
        regression into a failure instead of a hung suite.
        """
        if not hasattr(os, "mkfifo") or not hasattr(signal, "setitimer"):
            self.skipTest("mkfifo / setitimer unavailable")
        workspace = make_workspace(new_tmp(self))
        managed = workspace / "CLAUDE.md"
        managed.unlink()
        os.mkfifo(managed)

        def _blocked(signum, frame):
            raise AssertionError("derivation blocked on a non-regular managed path")

        previous = signal.signal(signal.SIGALRM, _blocked)
        signal.setitimer(signal.ITIMER_REAL, 15)
        try:
            rc, out, _ = capture(["status", str(workspace), "--json"])
            self.assertEqual(rc, SUCCESS)
            json.loads(out)
            rc, _, _ = capture(["audit", str(workspace), "--check-drift"])
            self.assertIn(rc, (SUCCESS, DRIFT_ERROR))
        finally:
            signal.setitimer(signal.ITIMER_REAL, 0)
            signal.signal(signal.SIGALRM, previous)

    def test_removal_survives_a_read_only_parent(self) -> None:
        """A refused unlink must not abort a run that already synchronized files."""
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            self.skipTest("root ignores directory permission bits")
        workspace = make_workspace(new_tmp(self))
        ghost = workspace / "skills/zz-ghost"
        ghost.mkdir()
        (ghost / "SKILL.md").write_text(
            '---\nname: zz-ghost\ndescription: "Trigger: orphan fixture."\n---\n',
            encoding="utf-8",
        )
        rc, _, _ = capture(["upgrade", str(workspace)])
        self.assertEqual(rc, SUCCESS)

        shutil.rmtree(ghost)
        commands_dir = workspace / ".opencode/commands"
        os.chmod(commands_dir, 0o555)
        self.addCleanup(os.chmod, commands_dir, 0o755)

        result = upgrade_module.upgrade(workspace)
        orphan = ".opencode/commands/zz-ghost.md"
        self.assertNotIn(orphan, result["removed"],
                         "a path that could not be deleted is not reported as removed")
        self.assertIn(orphan, result["stranded"],
                      "a refused removal must be reported, not swallowed")
        self.assertTrue((workspace / orphan).is_file())

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn(orphan, json.loads(out)["framework"]["drifted_files"],
                      "an undeletable stale file stays visible as drift and is retried later")

    def test_manifest_keys_can_never_escape_the_workspace(self) -> None:
        """A stored-manifest key is data, not a trusted path.

        Without a containment check the removal predicate would resolve a
        crafted ``..`` key outside the workspace and ``unlink`` a user's file.
        """
        workspace = make_workspace(new_tmp(self))
        victim = workspace.parent / "victim.txt"
        victim.write_text("must survive\n", encoding="utf-8")

        manifest_path = workspace / ".papersmith" / "manifest.json"
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        escape = f".opencode/commands/../../../{victim.name}"
        self.assertTrue((workspace / escape).resolve() == victim.resolve(),
                        "fixture must name a path outside the workspace")
        payload["files"][escape] = "0" * 64
        manifest_path.write_text(json.dumps(payload), encoding="utf-8")

        result = upgrade_module.upgrade(workspace)
        self.assertEqual(victim.read_text(encoding="utf-8"), "must survive\n")
        self.assertNotIn(escape, result["removed"])


class DamagedWorkspaceTotalityTests(unittest.TestCase):
    """Every managed path a damaged workspace can put in the way of a command.

    These are the residuals the Change B review left as pre-existing: the
    version marker, the write path, ``audit``'s read, and the workspace config.
    Each one previously either blocked forever or escaped as an untyped
    exception, and each is now closed by the same regular-file gate — a guarded
    read alone is not enough, because ``open(2)`` on a FIFO never returns and
    ``Path.is_file`` re-raises EACCES on CPython 3.11-3.13.
    """

    @contextlib.contextmanager
    def _alarm(self, message: str, seconds: int = 15):
        """Turn a regression into a failure instead of a hung suite."""
        if not hasattr(signal, "setitimer"):
            self.skipTest("setitimer unavailable")

        def _blocked(signum, frame):
            raise AssertionError(message)

        previous = signal.signal(signal.SIGALRM, _blocked)
        signal.setitimer(signal.ITIMER_REAL, seconds)
        try:
            yield
        finally:
            signal.setitimer(signal.ITIMER_REAL, 0)
            signal.signal(signal.SIGALRM, previous)

    @contextlib.contextmanager
    def _recorded_warnings(self):
        with _warnings.catch_warnings(record=True) as caught:
            _warnings.simplefilter("always")
            yield caught

    def test_a_fifo_at_the_version_marker_never_blocks(self) -> None:
        """The marker is a managed path, so it takes the same gate as the rest."""
        if not hasattr(os, "mkfifo"):
            self.skipTest("mkfifo unavailable")
        workspace = make_workspace(new_tmp(self))
        marker = workspace / ".papersmith" / "version"
        marker.unlink()
        os.mkfifo(marker)

        with self._alarm("a read blocked on a FIFO version marker"):
            rc, out, _ = capture(["status", str(workspace), "--json"])
            self.assertEqual(rc, SUCCESS)
            payload = json.loads(out)
        self.assertEqual(payload["framework"]["workspace_version"], "unknown")
        self.assertFalse(payload["framework"]["version_match"])

    def test_a_non_utf8_version_marker_is_a_default_not_a_traceback(self) -> None:
        """``UnicodeDecodeError`` is not an ``OSError``, so the old guard missed it."""
        workspace = make_workspace(new_tmp(self))
        (workspace / ".papersmith" / "version").write_bytes(b"\xff\xfe not utf-8")

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertEqual(json.loads(out)["framework"]["workspace_version"], "unknown")

    def test_upgrade_skips_a_rendered_path_occupied_by_a_fifo(self) -> None:
        """``apply_generated`` writes, so a FIFO there would block the write half.

        The write path runs after the kit copy has already mutated the workspace,
        so a hang or an abort here is worse than one on a read: it strands a
        half-synchronized workspace. The path is reported and left alone.
        """
        if not hasattr(os, "mkfifo"):
            self.skipTest("mkfifo unavailable")
        workspace = make_workspace(new_tmp(self))
        managed = workspace / "CLAUDE.md"
        managed.unlink()
        os.mkfifo(managed)

        with self._alarm("upgrade blocked writing a FIFO"):
            with self._recorded_warnings() as caught:
                result = upgrade_module.upgrade(workspace)
        self.assertNotIn("CLAUDE.md", result["changed_files"])
        self.assertIn("CLAUDE.md", result["unsynchronized"],
                      "a skipped write is surfaced to the caller, not only warned")
        stat_mode = managed.lstat().st_mode
        self.assertTrue(stat_module.S_ISFIFO(stat_mode), "the FIFO is left as it was")
        self.assertTrue(any("CLAUDE.md" in str(entry.message) for entry in caught),
                        "a skipped write is reported, not swallowed")

    def test_a_skipped_write_never_disappears_from_the_baseline(self) -> None:
        """The rewrite must not lose a path the live map omits.

        ``workspace_framework_files`` drops any path it cannot hash, so a
        baseline rewritten after a skip would lose the path from *both* sides of
        ``status``'s comparison and report a false "no drift" for a managed path
        that was never synchronized. The baseline keeps a marker instead, so
        ``status`` and ``audit`` agree.
        """
        if not hasattr(os, "mkfifo"):
            self.skipTest("mkfifo unavailable")
        workspace = make_workspace(new_tmp(self))
        managed = workspace / "CLAUDE.md"
        managed.unlink()
        os.mkfifo(managed)

        with self._alarm("upgrade blocked writing a FIFO"):
            with self._recorded_warnings():
                upgrade_module.upgrade(workspace)

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("CLAUDE.md", json.loads(out)["framework"]["drifted_files"],
                      "status must not report a false 'no drift' for a skipped path")

        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, DRIFT_ERROR)
        self.assertIn("CLAUDE.md", out)

    def test_a_written_but_unhashable_path_stays_visible_as_drift(self) -> None:
        """A write can succeed and still leave the path unhashable.

        A write-only regular file is overwritten successfully, so it is *not*
        "unsynchronized" — yet ``workspace_framework_files`` still cannot read it
        back. Sweeping the whole render set, rather than only the paths reported
        as unsynchronized, is what keeps this out of a false "no drift"; the
        FIFO case alone would pass either way.
        """
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            self.skipTest("root ignores file permission bits")
        workspace = make_workspace(new_tmp(self))
        managed = workspace / "CLAUDE.md"
        os.chmod(managed, 0o200)
        self.addCleanup(os.chmod, managed, 0o644)

        with self._recorded_warnings():
            result = upgrade_module.upgrade(workspace)
        self.assertNotIn("CLAUDE.md", result["unsynchronized"],
                         "the write succeeded, so this is not a skip")

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("CLAUDE.md", json.loads(out)["framework"]["drifted_files"],
                      "an unhashable managed path is drift, not silence")

        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, DRIFT_ERROR)
        self.assertIn("CLAUDE.md", out)

    def test_a_directory_at_a_rendered_path_is_reported_not_fatal(self) -> None:
        """``write_bytes`` on a directory raised ``IsADirectoryError`` untyped."""
        workspace = make_workspace(new_tmp(self))
        managed = workspace / "CLAUDE.md"
        managed.unlink()
        managed.mkdir()
        (managed / "keep.txt").write_text("user data\n", encoding="utf-8")

        with self._recorded_warnings() as caught:
            result = upgrade_module.upgrade(workspace)
        self.assertTrue((managed / "keep.txt").is_file(), "user data is untouched")
        self.assertNotIn("CLAUDE.md", result["changed_files"])
        self.assertTrue(any("CLAUDE.md" in str(entry.message) for entry in caught))

    def test_audit_agrees_with_status_on_an_unreadable_rendered_file(self) -> None:
        """A mode-000 *regular* file: the gate passes, the read does not.

        ``is_regular_file`` cannot see a mode that denies reading, so the read
        itself is guarded too. ``audit`` used to traceback on exactly the path
        ``status`` reported as drift.
        """
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            self.skipTest("root ignores file permission bits")
        workspace = make_workspace(new_tmp(self))
        managed = workspace / "CLAUDE.md"
        os.chmod(managed, 0o000)
        self.addCleanup(os.chmod, managed, 0o644)

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("CLAUDE.md", json.loads(out)["framework"]["drifted_files"])

        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, DRIFT_ERROR)
        self.assertIn("CLAUDE.md", out)

    def test_a_non_utf8_workspace_config_is_a_typed_error(self) -> None:
        """A config read is a user error, never an untyped decode traceback."""
        workspace = make_workspace(new_tmp(self))
        (workspace / ".papersmith" / "config.json").write_bytes(b"\xff\xfe not utf-8")

        with self.assertRaises(UserError):
            status_module.status(workspace)
        rc, _, err = capture(["status", str(workspace)])
        self.assertEqual(rc, USER_ERROR)
        self.assertIn("config.json", err)

    def test_a_non_utf8_papersmith_yaml_is_a_typed_error(self) -> None:
        workspace = make_workspace(new_tmp(self))
        (workspace / "papersmith.yaml").write_bytes(b"\xff\xfe not utf-8")

        with self.assertRaises(UserError):
            status_module.status(workspace)
        rc, _, err = capture(["status", str(workspace)])
        self.assertEqual(rc, USER_ERROR)
        self.assertIn("papersmith.yaml", err)

    def test_a_damaged_run_ledger_is_reported_not_fatal(self) -> None:
        """``is_file`` short-circuits a FIFO, but not an unreadable or non-UTF-8 file.

        The FIFO case was already safe here — the existence check returns before
        any open — so the guard belongs on the read: a mode-000 or non-UTF-8
        ledger aborted a command whose contract is explicitly best-effort.
        """
        workspace = make_workspace(new_tmp(self))
        ledger_path = workspace / ".papersmith" / "runs_ledger.jsonl"
        ledger_path.write_text('{"exit": 0}\n', encoding="utf-8")

        # The decode half needs no permission bits, so it runs even as root.
        ledger_path.write_bytes(b"\xff\xfe not utf-8")
        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertEqual(json.loads(out)["tests"]["recorded_runs"], 0,
                         "a damaged ledger is reported as absent, not as a crash")

        if hasattr(os, "geteuid") and os.geteuid() == 0:
            self.skipTest("root ignores file permission bits; the read half is unreachable")
        os.chmod(ledger_path, 0o000)
        self.addCleanup(os.chmod, ledger_path, 0o644)
        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        json.loads(out)


    def test_a_fifo_at_a_config_read_is_a_typed_error(self) -> None:
        """The config reads are the one path every command takes.

        ``generators`` imports ``core.config``, so this gate could not live in
        ``generators`` and be imported from there: it moved to ``core.fs`` to sit
        below both. Without it a FIFO here blocks every command in the tool.
        """
        if not hasattr(os, "mkfifo"):
            self.skipTest("mkfifo unavailable")
        workspace = make_workspace(new_tmp(self))
        for relpath in (".papersmith/config.json", "papersmith.yaml"):
            with self.subTest(relpath=relpath):
                target = workspace / relpath
                original = target.read_bytes()
                target.unlink()
                os.mkfifo(target)
                try:
                    with self._alarm(f"a read blocked on a FIFO {relpath}"):
                        rc, _, err = capture(["status", str(workspace)])
                        self.assertEqual(rc, USER_ERROR)
                        self.assertIn(target.name, err)
                        rc, _, _ = capture(["upgrade", str(workspace)])
                        self.assertEqual(rc, USER_ERROR)
                finally:
                    target.unlink()
                    target.write_bytes(original)

    def test_a_non_utf8_manifest_is_a_typed_error(self) -> None:
        """``status`` reads the manifest before the config the earlier fix typed."""
        workspace = make_workspace(new_tmp(self))
        (workspace / ".papersmith" / "manifest.json").write_bytes(b"\xff\xfe not utf-8")

        rc, _, err = capture(["status", str(workspace)])
        self.assertEqual(rc, USER_ERROR)
        self.assertIn("manifest.json", err)

    def test_a_non_utf8_kit_manifest_is_a_typed_error(self) -> None:
        kit = new_tmp(self) / "kit"
        kit.mkdir()
        (kit / "kit-manifest.json").write_bytes(b"\xff\xfe not utf-8")

        with self.assertRaises(UserError):
            manifest_module.load_kit_manifest(kit)

    def test_upgrade_never_blocks_on_a_fifo_version_marker(self) -> None:
        """The repair command must tolerate the marker every reader now tolerates."""
        if not hasattr(os, "mkfifo"):
            self.skipTest("mkfifo unavailable")
        workspace = make_workspace(new_tmp(self))
        marker = workspace / ".papersmith" / "version"
        marker.unlink()
        os.mkfifo(marker)

        with self._alarm("upgrade blocked writing the version marker"):
            rc, _, _ = capture(["upgrade", str(workspace)])
            self.assertEqual(rc, SUCCESS)

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn(".papersmith/version", json.loads(out)["framework"]["drifted_files"],
                      "an unwritable marker stays visible instead of vanishing")

    def test_upgrade_never_blocks_on_a_fifo_kit_path(self) -> None:
        """Kit synchronization runs *before* rendering, so it needs its own gate."""
        if not hasattr(os, "mkfifo"):
            self.skipTest("mkfifo unavailable")
        workspace = make_workspace(new_tmp(self))
        managed = workspace / "requirements.txt"
        self.assertTrue(managed.is_file(), "fixture needs a kit-managed path")
        managed.unlink()
        os.mkfifo(managed)

        with self._alarm("upgrade blocked copying over a FIFO"):
            rc, _, _ = capture(["upgrade", str(workspace)])
            self.assertEqual(rc, SUCCESS)

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("requirements.txt", json.loads(out)["framework"]["drifted_files"])

    def test_recording_a_run_never_blocks_on_a_fifo_ledger(self) -> None:
        """Bookkeeping must not fail a run whose own outcome is already decided."""
        if not hasattr(os, "mkfifo"):
            self.skipTest("mkfifo unavailable")
        workspace = make_workspace(new_tmp(self))
        ledger_path = workspace / ".papersmith" / "runs_ledger.jsonl"
        if ledger_path.exists():
            ledger_path.unlink()
        os.mkfifo(ledger_path)

        with self._alarm("recording a run blocked on a FIFO ledger"):
            self.assertFalse(run_ledger.append(workspace, {"profile": "smoke", "exit": 0}))

    def test_an_unsearchable_scan_directory_never_breaks_status(self) -> None:
        """The scan helpers are best-effort too: they report, they never abort."""
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            self.skipTest("root ignores directory permission bits")
        workspace = make_workspace(new_tmp(self))
        for relpath in ("implementations", "kaggle-inbox"):
            with self.subTest(relpath=relpath):
                target = workspace / relpath
                target.mkdir(exist_ok=True)
                os.chmod(target, 0o000)
                self.addCleanup(os.chmod, target, 0o755)
                rc, out, _ = capture(["status", str(workspace), "--json"])
                self.assertEqual(rc, SUCCESS)
                json.loads(out)


    def test_a_preserved_path_never_becomes_permanent_drift(self) -> None:
        """A run never delivers a preserved path, so it must not demand one.

        ``guidance/**`` belongs to the user. Recording a marker for one the
        workspace does not have turns a self-clearing report into a permanent
        one: ``upgrade`` skips preserved paths on every run, so no command could
        ever clear it.

        Nothing in the real ``KIT_ENTRIES`` overlaps a preserve pattern any
        more (``guidance/paper-guide`` and ``package.json`` were the last two
        members that did, and both were removed from ``KIT_ENTRIES`` on
        purpose — see ``manifest.KIT_ENTRIES``'s own docstring). The invariant
        this test guards is still real defensive code in
        :func:`manifest.synchronized_paths`, so a single synthetic member is
        patched in here to recreate the overlap without depending on the kit
        happening to ship one.
        """
        workspace = make_workspace(new_tmp(self))
        kit_root = resolve_and_validate()
        with mock.patch.object(manifest_module, "KIT_ENTRIES",
                               manifest_module.KIT_ENTRIES + ("README.md",)):
            preserved = sorted(relpath for relpath in manifest_module.kit_files(kit_root)
                               if manifest_module.is_preserved(relpath))
            self.assertTrue(preserved, "the patched kit entry must ship a preserved path")
            victim = preserved[0]
            (workspace / victim).unlink()

            with self._recorded_warnings():
                upgrade_module.upgrade(workspace)

            manifest_path = workspace / ".papersmith" / "manifest.json"
            stored = json.loads(manifest_path.read_text(encoding="utf-8"))["files"]
            self.assertNotEqual(stored.get(victim), "unsynchronized",
                                "a user-owned path is not the framework's to demand")
            rc, out, _ = capture(["status", str(workspace), "--json"])
            self.assertEqual(rc, SUCCESS)
            self.assertNotIn(victim, json.loads(out)["framework"]["drifted_files"])

    def test_an_unreadable_kit_path_is_reported_not_fatal(self) -> None:
        """The kit fast path hashes the destination, and a mode-000 file raises.

        That hash is inside the repair command and runs after earlier kit files
        have been written, so an untyped ``PermissionError`` here aborts a
        half-synchronized workspace.
        """
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            self.skipTest("root ignores file permission bits")
        workspace = make_workspace(new_tmp(self))
        managed = workspace / "requirements.txt"
        self.assertTrue(managed.is_file(), "fixture needs a kit-managed path")
        os.chmod(managed, 0o000)
        self.addCleanup(os.chmod, managed, 0o644)

        with self._recorded_warnings():
            result = upgrade_module.upgrade(workspace)
        self.assertIn("requirements.txt", result["unsynchronized"])

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("requirements.txt", json.loads(out)["framework"]["drifted_files"])


    def test_an_already_deleted_orphan_clears_instead_of_stranding(self) -> None:
        """An orphan the user already removed must clear, not be retried forever.

        The orphan predicate selects stored dynamic keys without testing
        existence, so treating "absent" as "undeletable" re-marks the path on
        every run: a marker the live map can never show is drift no ``upgrade``
        can clear. Deleting the generated command yourself is the natural thing
        to do after removing a local skill.
        """
        workspace = make_workspace(new_tmp(self))
        ghost = workspace / "skills/zz-ghost"
        ghost.mkdir()
        (ghost / "SKILL.md").write_text(
            '---\nname: zz-ghost\ndescription: "Trigger: orphan fixture."\n---\n',
            encoding="utf-8",
        )
        with self._recorded_warnings():
            upgrade_module.upgrade(workspace)
        shutil.rmtree(ghost)
        for harness in (".opencode/commands", ".claude/commands"):
            (workspace / harness / "zz-ghost.md").unlink()

        with self._recorded_warnings():
            result = upgrade_module.upgrade(workspace)
        self.assertEqual(result["stranded"], [], "an absent path is already removed")
        self.assertIn(".opencode/commands/zz-ghost.md", result["removed"])

        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        self.assertEqual([p for p in json.loads(out)["framework"]["drifted_files"]
                          if "zz-ghost" in p], [],
                         "the report clears and does not come back")
        with self._recorded_warnings():
            upgrade_module.upgrade(workspace)
        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual([p for p in json.loads(out)["framework"]["drifted_files"]
                          if "zz-ghost" in p], [])

    def test_a_read_only_managed_write_is_a_typed_error(self) -> None:
        """A bare ``write_text`` mid-run escaped as an uncaught PermissionError.

        ``upgrade`` writes the config and then the manifest, both after the kit
        copy has already mutated the workspace, so an untyped crash there leaves
        a half-synchronized tree and no diagnosis.
        """
        if hasattr(os, "geteuid") and os.geteuid() == 0:
            self.skipTest("root ignores file permission bits")
        workspace = make_workspace(new_tmp(self))
        managed = workspace / ".papersmith" / "manifest.json"
        os.chmod(managed, 0o444)
        self.addCleanup(os.chmod, managed, 0o644)

        rc, _, err = capture(["upgrade", str(workspace)])
        self.assertEqual(rc, USER_ERROR)
        self.assertIn("manifest.json", err)


class TargetCommandTests(unittest.TestCase):

    def test_target_list_set_and_check_round_trip(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, out, _ = capture(["target", "list", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("local-workstation: local *", out)
        self.assertIn("kaggle-gpu-pool: kaggle", out)
        self.assertIn("slurm-cluster: remote-ssh", out)

        rc, out, _ = capture(["target", "set", "local-workstation", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("Active target: local-workstation (local)", out)

        rc, out, _ = capture(["target", "check", "local-workstation", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        result = ast.literal_eval(out.strip())
        self.assertEqual(result["provider"], "local")
        self.assertTrue(result["reachable"])

    def test_target_set_refuses_an_unknown_name(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, _, err = capture(["target", "set", "gpu-cloud", str(workspace)])
        self.assertEqual(rc, USER_ERROR)
        self.assertIn("unknown compute target", err)


class RunCommandTests(unittest.TestCase):

    def test_run_dry_run_records_a_row_without_dispatching(self) -> None:
        workspace = make_workspace(new_tmp(self))
        dispatched = False

        def _fail_if_dispatched(*args, **kwargs):
            nonlocal dispatched
            dispatched = True
            raise AssertionError("dry-run dispatched a subprocess")

        with mock.patch("papersmith.core.executor.subprocess.run",
                        side_effect=_fail_if_dispatched):
            rc, out, err = capture(["run", "smoke_and_invariants", "--dry-run", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertFalse(dispatched)
        self.assertIn("dry-run: no job was dispatched", err)
        payload = json.loads(out)
        self.assertTrue(payload["jobs"][0]["dry_run"])
        self.assertTrue(run_ledger.read(workspace)[0]["dry_run"])


class AuditCommandTests(unittest.TestCase):

    def test_audit_detects_drift_and_never_repairs_it(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("drift: clean", out)

        claude = workspace / "CLAUDE.md"
        claude.write_text(claude.read_text(encoding="utf-8") + "\n<!-- audit probe -->\n",
                          encoding="utf-8")
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, DRIFT_ERROR)
        self.assertIn("CLAUDE.md", out)
        self.assertIn("<!-- audit probe -->", claude.read_text(encoding="utf-8"))


class RemoteCommandTests(unittest.TestCase):

    def test_remote_push_refuses_before_its_required_flags_are_named(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, _, err = capture(["remote", "push", str(workspace)])
        self.assertEqual(rc, USER_ERROR)
        self.assertIn("remote push requires", err)

    def test_remote_status_refuses_an_unresolvable_job_target(self) -> None:
        workspace = make_workspace(new_tmp(self))
        missing = workspace / "implementations" / "missing"
        rc, _, err = capture(
            ["remote", "status", "--target", str(missing),
             "--entrypoint", "Notebooks/a.ipynb", str(workspace)]
        )
        self.assertNotEqual(rc, SUCCESS)
        self.assertIn("does not resolve to an existing directory", err)
        self.assertFalse(missing.exists(), "a refused status must touch nothing")


class DeliberateImplementCommandTests(unittest.TestCase):

    def test_deliberate_engine_runs_and_implement_probes_in_one_workspace(self) -> None:
        workspace = make_workspace(new_tmp(self))
        link_node_modules(workspace)
        token = f"series-{os.getpid()}"

        rc, out, _ = capture([
            "deliberate", str(workspace), "--action", "init",
            "--instruction", f"{token}. The series walks the workspace engine.",
        ])
        self.assertEqual(rc, SUCCESS)
        created = json.loads(out)
        target = created["targetFilename"]
        self.assertTrue(target.endswith("-r01.md"))
        self.assertTrue((workspace / "proposals" / target).is_file())

        rc, out, _ = capture(["deliberate", str(workspace), "--action", "status"])
        self.assertEqual(rc, SUCCESS)
        self.assertEqual(json.loads(out)["latest"], target)

        make_demo_target(workspace)
        rc, out, _ = capture([
            "implement", str(workspace), "--action", "probe",
            "--target", "implementations/demo", "--name", "Demo",
        ])
        self.assertEqual(rc, SUCCESS)
        payload = json.loads(out)
        self.assertEqual(payload["status"], "ok")
        self.assertTrue(payload["nextStep"])
        self.assertEqual(list((workspace / "implementations" / "demo").rglob("*.ipynb")), [])


class IngestCommandTests(unittest.TestCase):

    def test_ingest_stubbed_lands_markdown_figure_and_index(self) -> None:
        workspace = make_workspace(new_tmp(self))
        with stub_extract():
            rc, out, _ = capture(["ingest", str(FIXTURE_PDF), str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("Ingested:", out)
        paper_dir = workspace / "guidance" / "reference-papers" / "paper"
        markdown = (paper_dir / "paper.md").read_text(encoding="utf-8")
        self.assertIn(r"\tag", markdown)
        self.assertTrue((paper_dir / "_page_1_Figure_1.png").is_file())
        index = json.loads(
            (workspace / "guidance" / "reference-papers" / "index.json").read_text(encoding="utf-8")
        )
        self.assertTrue(any(entry["id"] == "paper" for entry in index["entries"]))


class LiveSmokeScriptTests(unittest.TestCase):
    """The opt-in live smoke is a contract of this series, not a suggestion."""

    SCRIPT = REPO_ROOT / "scripts" / "cli-paper-live-smoke.sh"

    def test_script_exists_executable_and_covers_every_command(self) -> None:
        self.assertTrue(self.SCRIPT.is_file(), "missing scripts/cli-paper-live-smoke.sh")
        self.assertTrue(os.access(self.SCRIPT, os.X_OK), "live smoke must be executable")
        text = self.SCRIPT.read_text(encoding="utf-8")
        for command in COMMANDS:
            self.assertIn(command, text, f"live smoke must cover {command}")
        self.assertIn("PAPERSMITH_LIVE", text, "live smoke must be explicitly opt-in")

    def test_script_refuses_to_run_without_opt_in(self) -> None:
        env = {key: value for key, value in os.environ.items() if key != "PAPERSMITH_LIVE"}
        completed = subprocess.run(
            ["bash", str(self.SCRIPT), str(new_tmp(self))],
            capture_output=True, text=True, timeout=60, env=env,
        )
        self.assertNotEqual(completed.returncode, 0, "live smoke ran without PAPERSMITH_LIVE")
        self.assertIn("PAPERSMITH_LIVE", completed.stderr + completed.stdout)

    def test_hermetic_smoke_wrapper_still_exists(self) -> None:
        hermetic = REPO_ROOT / "scripts" / "cli-paper-smoke.sh"
        self.assertTrue(hermetic.is_file())
        self.assertTrue(os.access(hermetic, os.X_OK))


class SeriesRegistrationTests(unittest.TestCase):
    """The series registers itself in the SDD testing layers it belongs to."""

    def test_series_files_are_registered_in_config(self) -> None:
        text = (REPO_ROOT / "openspec" / "config.yaml").read_text(encoding="utf-8")
        for name in (
            "test_workspace_commands_e2e",
            "test_workspace_skills_e2e",
            "test_workspace_agents_e2e",
        ):
            self.assertIn(name, text, f"{name} must appear in openspec/config.yaml")
