"""Publishing to an index is the first distribution channel that cannot be fixed.

Until now a user installed from a git URL, so a mistake was one force-reinstall
away from being gone. A version published to PyPI is final: it cannot be
replaced, only yanked, and the number is spent forever. The failure mode that
matters is therefore not "the upload broke" -- that is loud -- but "the upload
succeeded and shipped something that does not work", which is silent until
somebody installs it.

This file guards the one way that can happen here. `src/papersmith/_kit/` is
GENERATED by `scripts/build-kit.py` and gitignored, while `pyproject.toml`
declares it as package data. A clean checkout therefore builds a wheel that is
structurally valid, passes every other test, uploads without complaint, and
then refuses at runtime with exit 2 and `no kit` -- because the directory the
manifest promised was empty when the archive was written.

So the questions here are:

  metadata    the page a user lands on says who publishes this, under which
              licence, and where the source lives
  kit         the built artifacts actually CONTAIN the generated kit, asked of
              the archives rather than of the manifest that promises it
  workflow    the publishing workflow builds the kit before packaging, and
              authenticates without a long-lived secret

The kit question is asked by building, because a manifest that declares
`_kit/**/*` and a tree where that glob matches nothing both read identically in
`pyproject.toml`.
"""

import shutil
import subprocess
import sys
import tarfile
import tempfile
import tomllib
import unittest
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PYPROJECT = REPO / "pyproject.toml"
WORKFLOW = REPO / ".github" / "workflows" / "publish.yml"

#: Files the kit must carry into an artifact for `papersmith init` to work at
#: all. `kit-manifest.json` is what `kit.resolve_and_validate` reads first, so
#: an archive without it produces the `SOURCE_ERROR` exit 2 this file exists to
#: prevent.
KIT_SENTINELS = (
    "papersmith/_kit/kit-manifest.json",
    "papersmith/_kit/requirements.txt",
)


def pyproject() -> dict:
    with PYPROJECT.open("rb") as handle:
        return tomllib.load(handle)


class PublishingMetadataTests(unittest.TestCase):
    """The fields that decide what a stranger sees on the project page."""

    def setUp(self) -> None:
        self.project = pyproject()["project"]

    def test_names_who_publishes_it(self) -> None:
        authors = self.project.get("authors")
        self.assertTrue(
            authors,
            "pyproject declares no authors, so the published page attributes "
            "this to nobody")
        for author in authors:
            self.assertTrue(
                author.get("name"),
                f"an author entry without a name: {author!r}")

    def test_declares_a_licence_the_index_can_read(self) -> None:
        licence = self.project.get("license")
        self.assertTrue(
            licence,
            "pyproject declares no license. A LICENSE file alone leaves the "
            "index showing no licence, which is what a cautious institution "
            "checks first")
        self.assertTrue(
            (REPO / "LICENSE").is_file(), "the declared licence has no LICENSE file")

    def test_carries_the_readme_as_the_long_description(self) -> None:
        readme = self.project.get("readme")
        self.assertTrue(
            readme,
            "pyproject declares no readme, so the project page would be the "
            "one-line summary and nothing else")
        name = readme if isinstance(readme, str) else readme.get("file", "")
        self.assertTrue((REPO / name).is_file(), f"readme {name!r} does not exist")

    def test_points_at_its_own_source(self) -> None:
        urls = self.project.get("urls") or {}
        self.assertTrue(
            urls, "pyproject declares no project URLs, so the page links nowhere")
        joined = " ".join(urls.values())
        self.assertIn(
            "github.com", joined,
            "no project URL points at the source repository")

    def test_classifies_itself_for_the_index(self) -> None:
        classifiers = self.project.get("classifiers") or []
        self.assertTrue(classifiers, "pyproject declares no classifiers")
        prefixes = {value.split(" :: ")[0] for value in classifiers}
        for required in ("Programming Language", "Intended Audience", "Topic"):
            self.assertIn(
                required, prefixes,
                f"no {required} classifier; the index cannot categorize this")

    def test_states_the_licence_once(self) -> None:
        """PEP 639 replaced the `License ::` classifier with an SPDX expression,
        and setuptools refuses a build carrying both. Declaring the licence
        twice is therefore not redundancy -- it is a build that fails.
        """
        classifiers = self.project.get("classifiers") or []
        legacy = [value for value in classifiers if value.startswith("License ::")]
        self.assertEqual(
            legacy, [],
            "a `License ::` classifier sits beside the SPDX license "
            "expression; setuptools rejects that combination outright")

    def test_still_derives_the_version_rather_than_restating_it(self) -> None:
        # Guarded here as well as in test_version_sources, because adding
        # publishing metadata is exactly the edit that tempts someone to pin a
        # literal version beside the authors.
        self.assertIn("version", pyproject()["project"].get("dynamic", []))
        self.assertNotIn("version", pyproject()["project"])


class BuiltArtifactsCarryTheKitTests(unittest.TestCase):
    """Asked of the archives, because the manifest cannot answer it.

    `python -m build` is required rather than skipped-when-missing: a skip here
    would read as a pass on the one question whose wrong answer ships a broken
    install.
    """

    @classmethod
    def setUpClass(cls) -> None:
        if not (REPO / "src" / "papersmith" / "_kit" / "kit-manifest.json").is_file():
            raise unittest.SkipTest(
                "the generated kit is absent from this checkout; run "
                "`python scripts/build-kit.py` first. This is a skip rather "
                "than a failure because the kit is gitignored by design")
        probe = subprocess.run(
            [sys.executable, "-c", "import build"], capture_output=True)
        if probe.returncode != 0:
            raise unittest.SkipTest(
                "`build` is not importable by this interpreter, so no artifact "
                "can be produced to inspect")

        cls._tmp = tempfile.mkdtemp(prefix="papersmith-dist-")
        result = subprocess.run(
            [sys.executable, "-m", "build", "--outdir", cls._tmp],
            cwd=REPO, capture_output=True, text=True)
        if result.returncode != 0:
            raise AssertionError(
                f"`python -m build` failed:\n{result.stdout[-2000:]}\n{result.stderr[-2000:]}")
        out = Path(cls._tmp)
        cls.wheel = next(iter(sorted(out.glob("*.whl"))), None)
        cls.sdist = next(iter(sorted(out.glob("*.tar.gz"))), None)

    @classmethod
    def tearDownClass(cls) -> None:
        if hasattr(cls, "_tmp"):
            shutil.rmtree(cls._tmp, ignore_errors=True)

    def test_a_wheel_and_an_sdist_were_produced(self) -> None:
        self.assertIsNotNone(self.wheel, "no wheel was built")
        self.assertIsNotNone(self.sdist, "no sdist was built")

    def test_the_wheel_carries_the_generated_kit(self) -> None:
        with zipfile.ZipFile(self.wheel) as archive:
            names = set(archive.namelist())
        for sentinel in KIT_SENTINELS:
            self.assertIn(
                sentinel, names,
                f"the wheel has no {sentinel}. An install from it would reach "
                "`papersmith init` and exit 2 with a kitless install")
        skills = [name for name in names if name.startswith("papersmith/_kit/skills/")]
        self.assertTrue(skills, "the wheel carries no kit skills")

    def test_the_sdist_carries_the_generated_kit(self) -> None:
        with tarfile.open(self.sdist) as archive:
            names = set(archive.getnames())
        # An sdist nests everything under `<name>-<version>/`, so the sentinels
        # are matched by suffix rather than by exact path.
        for sentinel in KIT_SENTINELS:
            self.assertTrue(
                any(name.endswith(sentinel.replace("papersmith/", "src/papersmith/"))
                    or name.endswith(sentinel) for name in names),
                f"the sdist has no {sentinel}")

    def test_every_file_stays_under_the_index_limit(self) -> None:
        # PyPI refuses a file over 100 MB. Both artifacts are single-digit
        # megabytes today; this fails early if something starts vendoring.
        limit = 100 * 1024 * 1024
        for artifact in (self.wheel, self.sdist):
            size = artifact.stat().st_size
            self.assertLess(
                size, limit,
                f"{artifact.name} is {size / 1024 / 1024:.1f} MB, over the "
                "index's 100 MB per-file limit")


class PublishingWorkflowTests(unittest.TestCase):
    """The workflow has to do two things no reviewer can see from a diff alone."""

    def setUp(self) -> None:
        if not WORKFLOW.is_file():
            self.fail(
                f"no publishing workflow at {WORKFLOW.relative_to(REPO)}; "
                "publishing by hand is how a release ships without its kit")
        self.text = WORKFLOW.read_text(encoding="utf-8")

    def test_builds_the_kit_before_packaging(self) -> None:
        self.assertIn(
            "scripts/build-kit.py", self.text,
            "the workflow never runs scripts/build-kit.py. The kit is "
            "gitignored, so a runner checks out a tree without it and would "
            "publish an artifact whose declared package data matches nothing")
        kit_at = self.text.index("scripts/build-kit.py")
        # `python` or `python3`: the workflow names a concrete interpreter and
        # which one it is is not this test's business.
        build_at = min(
            (self.text.index(token) for token in ("python -m build", "python3 -m build")
             if token in self.text),
            default=-1)
        self.assertNotEqual(
            build_at, -1, "the workflow never runs `python -m build`")
        self.assertLess(
            kit_at, build_at,
            "the kit is built after the package, so the package cannot "
            "contain it")

    def test_authenticates_without_a_long_lived_secret(self) -> None:
        self.assertIn(
            "id-token: write", self.text,
            "the workflow does not request the OIDC id-token permission, so "
            "it cannot use Trusted Publishing")
        for forbidden in ("PYPI_API_TOKEN", "password:"):
            self.assertNotIn(
                forbidden, self.text,
                f"the workflow references {forbidden!r}. Trusted Publishing "
                "exists so no durable credential has to live in this "
                "repository")

    def test_runs_the_suites_before_it_publishes(self) -> None:
        self.assertIn(
            "npm run test:node", self.text,
            "the workflow publishes without running the Node suite")

    def test_is_triggered_by_a_release_rather_than_by_every_push(self) -> None:
        head = self.text.split("jobs:", 1)[0]
        self.assertTrue(
            "release:" in head or "tags:" in head or "workflow_dispatch:" in head,
            "the workflow has no release, tag or manual trigger; publishing on "
            "every push would burn a version number per commit")
        self.assertNotIn(
            "branches:\n      - main", head,
            "the workflow publishes on pushes to main")


if __name__ == "__main__":
    unittest.main()
