import type { CleanupLevel,EffectiveOperationProfile,Intent,OperationRisk } from './types.js'; import { roleBudgets } from './role-budget.js';
export type OperationProfile={destructive:boolean;maxModels:number;maxRoleAuthorizations:number;maxMutations:number;maxPatches:number;maxContextFragments:number;maxContextBytes:number;maxParallelModelCalls:number};
const local={maxContextFragments:8,maxContextBytes:32000,maxParallelModelCalls:1};
const profile=(intent:Intent,destructive=false):OperationProfile=>({destructive,maxModels:roleBudgets[intent].maxModelCalls,maxRoleAuthorizations:roleBudgets[intent].maxRoleAuthorizations,maxMutations:roleBudgets[intent].maxMutations,maxPatches:roleBudgets[intent].maxPatchCount,...local});
export const operationSpec:Record<Intent,OperationProfile>={MODIFY:profile('MODIFY'),INSERT:profile('INSERT'),DELETE:profile('DELETE',true),MOVE:profile('MOVE',true),COPY:profile('COPY'),CONCEPTUAL_REVISION:profile('CONCEPTUAL_REVISION'),REVIEW:profile('REVIEW'),DELIBERATE:profile('DELIBERATE'),WITHDRAW_REVISION:profile('WITHDRAW_REVISION',true),RESTORE_WITHDRAWN_REVISION:profile('RESTORE_WITHDRAWN_REVISION',true),AMBIGUOUS:profile('AMBIGUOUS')};
export function operationProfile(intent:Intent):OperationProfile|undefined{return operationSpec[intent]}
export type EffectiveProfileInput={intent:Intent;cleanupLevel:CleanupLevel;semanticChange?:boolean;conceptualRisk?:OperationRisk;requestedReview?:boolean;requestedDeliberation?:boolean;successorCompositeTarget?:boolean};
export function resolveEffectiveOperationProfile(input:EffectiveProfileInput):EffectiveOperationProfile {const base=operationProfile(input.intent);if(!base)throw new Error('UNSUPPORTED_OPERATION_PROFILE');const semanticCleanup=input.cleanupLevel==='SEMANTIC';const successorCompositeTarget=input.successorCompositeTarget===true;const risk=input.conceptualRisk??(input.intent==='CONCEPTUAL_REVISION'?'MEDIUM':'LOW');const maxCleanupRanges=semanticCleanup||input.cleanupLevel==='STRUCTURAL'?3:0;return {intent:input.intent,cleanupLevel:input.cleanupLevel,maxModelCalls:semanticCleanup?1:base.maxModels,maxPlannerCalls:semanticCleanup?1:(input.intent==='CONCEPTUAL_REVISION'||input.semanticChange?1:0),maxRoleAuthorizations:semanticCleanup?1:base.maxRoleAuthorizations,maxMutations:base.maxMutations,maxPatchCount:successorCompositeTarget?1:semanticCleanup||input.cleanupLevel==='STRUCTURAL'?4:base.maxPatches,maxCleanupRanges,requiresTutor:input.intent==='CONCEPTUAL_REVISION'&&Boolean(input.semanticChange),requiresReviewer:Boolean(input.requestedReview),operationRisk:risk};}
export function reviewerRequired(intent:Intent,instruction:string,tutorRisk?:string){return intent==='REVIEW'||/reviewer|revisi[oó]n independiente/i.test(instruction)||tutorRisk==='HIGH'||(intent==='CONCEPTUAL_REVISION'&&/alto riesgo|varias secciones/i.test(instruction));}
