import { mkdtemp, mkdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createProposalWorkspaceTool, createDocumentOperationGuard } from './proposal-workspace.js';
import { PaperProposalOrchestrator } from './orchestrator.js';
import { ProposalWorkspaceAdapter } from './proposal-workspace-adapter.js';
import { loadDocumentState } from './document-state.js';
import { getRuntimeMetrics, resetRuntimeMetrics } from './runtime-metrics.js';
import { getMutationLockMetrics, resetMutationLockMetrics } from './mutation-lock.js';
import { runConsistencyAudit } from './consistency-audit.js';
import { runPaperProposalSelfAudit } from './self-audit.js';
import { resolveSourceAndDestination } from './target-resolver.js';

const planner={plan:async(input:any)=>{const target=input.target??{entryId:input.sourceEntryIds?.[0]};if(input.intent.intent==='MOVE'||input.intent.intent==='COPY')return {transformedContent:'Inserted paragraph.'};return {actions:[{kind:'replace',targetEntryId:target.entryId,replacementText:input.intent.intent==='CONCEPTUAL_REVISION'?'Gamma conceptually revised paragraph.':'Revised paragraph.'}],expectedEffects:[]}}};
const tutor={assess:async()=>({decision:'ALLOW',summary:'ok',riskLevel:'LOW',unresolvedQuestions:[]})};
const reviewer={review:async()=>({decision:'ALLOW',summary:'ok',riskLevel:'LOW',unresolvedQuestions:[]})};
let operationSequence=0;
async function runtime(root:string,id:string){const guard=createDocumentOperationGuard(root);const workspace=createProposalWorkspaceTool(root,{operationGuard:guard});const adapter=new ProposalWorkspaceAdapter(root,guard,workspace,()=>`${id}-${++operationSequence}`);return new PaperProposalOrchestrator(root,adapter,undefined,planner,{tutor,reviewer});}
async function paragraph(root:string,text:string){const lookup=await runtime(root,'lookup');const filename=await lookup.latest();const state=await loadDocumentState(root,filename!);return state.structuralIndex.entries.find((entry:any)=>entry.type==='paragraph'&&state.documentBytes.subarray(entry.startByte,entry.endByte).toString().includes(text))?.entryId;}
export async function runPaperProposalSmoke(){const root=await mkdtemp(join(tmpdir(),'pp-v2-smoke-'));await mkdir(join(root,'proposals'),{recursive:true});const seed=createProposalWorkspaceTool(root);await seed.execute('seed',{action:'write',resource:'proposal',slug:'r01',content:'# Proposal\n\nAlpha paragraph.\n\nBeta paragraph.\n\n## Results\n\nGamma paragraph.\n'});resetRuntimeMetrics();resetMutationLockMetrics();let orchestrator=await runtime(root,'smoke-a');const operations:any[]=[];async function execute(request:any){const value=await orchestrator.execute(request);operations.push(value);if(value.status!=='published')throw new Error(`SMOKE_OPERATION_FAILED:${request.instruction}:${value.reason??value.status}`);return value}
let alpha=await paragraph(root,'Alpha');await execute({instruction:'modifica Alpha paragraph.',selectedEntryId:alpha});let revised=await paragraph(root,'Revised');await execute({instruction:'inserta literal note after Revised paragraph.',selectedEntryId:revised,literalContent:'\n\nInserted paragraph.\n'});let latestForMove=await orchestrator.latest();let moveState=await loadDocumentState(root,latestForMove!);let insertedForMove=moveState.structuralIndex.entries.find((entry:any)=>entry.type==='paragraph'&&moveState.documentBytes.subarray(entry.startByte,entry.endByte).toString()==='Inserted paragraph.');let betaForMove=moveState.structuralIndex.entries.find((entry:any)=>entry.type==='paragraph'&&moveState.documentBytes.subarray(entry.startByte,entry.endByte).toString()==='Beta paragraph.');if(!insertedForMove||!betaForMove)throw new Error('SMOKE_FIXTURE_SELECTOR_MISSING');const moveCandidates=resolveSourceAndDestination(moveState,insertedForMove.entryId,betaForMove.entryId);if(moveCandidates.sourceCandidates.length!==1||moveCandidates.destinationCandidates.length!==1||moveState.documentSha256!==moveState.derivedStateManifest.documentSha256)throw new Error('SMOKE_FIXTURE_SELECTOR_AMBIGUOUS');await execute({instruction:'mueve contenido seleccionado.',sourceQuery:insertedForMove.entryId,destinationQuery:betaForMove.entryId,position:'after'});let insertedForCopy=await paragraph(root,'Inserted');let gammaForCopy=await paragraph(root,'Gamma');await execute({instruction:'copia contenido seleccionado.',sourceQuery:insertedForCopy,destinationQuery:gammaForCopy,position:'after'});let inserted=await paragraph(root,'Inserted');await execute({instruction:'elimina inserted paragraph.',selectedEntryId:inserted});let beta=await paragraph(root,'Beta');await execute({instruction:'elimina beta paragraph con cleanup semántico.',selectedEntryId:beta});let gamma=await paragraph(root,'Gamma');await execute({instruction:'revisión conceptual de Gamma paragraph.',selectedEntryId:gamma});const deliberate=await orchestrator.execute({instruction:'delibera sobre Gamma paragraph.',selectedEntryId:gamma});if(deliberate.mutations!==0)throw new Error('SMOKE_DELIBERATE_MUTATED');orchestrator=undefined as any;resetRuntimeMetrics();resetMutationLockMetrics();orchestrator=await runtime(root,'smoke-b');gamma=await paragraph(root,'Gamma');await execute({instruction:'modifica Gamma paragraph.',selectedEntryId:gamma});const latest=await orchestrator.latest();const consistency=await runConsistencyAudit({projectRoot:root});const selfAudit=await runPaperProposalSelfAudit({projectRoot:root});return {root,latest,operations,consistency,selfAudit,metrics:getRuntimeMetrics(),locks:getMutationLockMetrics(),latestBytes:await readFile(join(root,'proposals',latest!),'utf8')};}
