import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'; import { dirname, join } from 'node:path';
import { isAcceptedParserVersion, sha256, type DerivedStateManifest, type DocumentState, type RevisionReceipt } from './types.js';
import type { InitialPublicationReceipt } from './revision-receipt.js';
type Stored={manifest:DerivedStateManifest;structuralIndex:DocumentState['structuralIndex'];referenceIndex:DocumentState['referenceIndex'];symbolIndex:DocumentState['symbolIndex'];conceptIndex:DocumentState['conceptIndex']};
function validatePublicationReceipt(value:any,manifest:DerivedStateManifest):value is RevisionReceipt|InitialPublicationReceipt{return !!value&&value.targetFilename===manifest.documentFilename&&value.targetRevision===manifest.revision&&value.documentShaAfter===manifest.documentSha256&&value.derivedStateStatus==='COMMITTED'&&(value.kind===undefined||value.kind==='INITIAL_PUBLICATION')}
export function derivedStatePath(root:string,filename:string){return join(root,'.proposal-deliberation','state',`${filename}.json`)}
export function receiptPath(root:string,filename:string){return join(root,'.proposal-deliberation','receipts',`${filename}.json`)}
export function validateStoredState(value:any,filename:string,sha:string,parserVersion:string,bytes?:Buffer):value is Stored {const m=value?.manifest,entries=value?.structuralIndex?.entries;const hashes=!!m&&m.structuralIndexSha256===sha256(JSON.stringify(value.structuralIndex))&&m.referenceIndexSha256===sha256(JSON.stringify(value.referenceIndex))&&m.symbolIndexSha256===sha256(JSON.stringify(value.symbolIndex))&&m.conceptIndexSha256===sha256(JSON.stringify(value.conceptIndex));const ranges=!bytes||Array.isArray(entries)&&entries.every((e:any)=>Number.isInteger(e.startByte)&&Number.isInteger(e.endByte)&&e.startByte>=0&&e.endByte>=e.startByte&&e.endByte<=bytes.length&&e.textSha256===sha256(bytes.subarray(e.startByte,e.endByte)));return !!m&&m.documentFilename===filename&&m.documentSha256===sha&&isAcceptedParserVersion(m.parserVersion,parserVersion)&&['VALID','COMMITTED'].includes(m.status)&&hashes&&ranges;}
async function atomic(path:string,value:unknown){await mkdir(dirname(path),{recursive:true});const temp=`${path}.${process.pid}.${Math.random().toString(36).slice(2)}.tmp`;await writeFile(temp,JSON.stringify(value));await rename(temp,path)}
export async function loadDerivedState(root:string,filename:string,sha:string,parserVersion:string,bytes?:Buffer){try{const value=JSON.parse(await readFile(derivedStatePath(root,filename),'utf8'));if(!validateStoredState(value,filename,sha,parserVersion,bytes))return undefined;if(value.manifest.status==='COMMITTED'){const receipt=JSON.parse(await readFile(receiptPath(root,filename),'utf8'));if(!validatePublicationReceipt(receipt,value.manifest))return undefined;}return value}catch{return undefined}}
export async function saveDerivedState(root:string,state:DocumentState,status:DerivedStateManifest['status']='VALID'){const manifest={...state.derivedStateManifest,status};const stored:Stored={manifest,structuralIndex:state.structuralIndex,referenceIndex:state.referenceIndex,symbolIndex:state.symbolIndex,conceptIndex:state.conceptIndex};const existing=await loadDerivedState(root,state.filename,state.documentSha256,state.parserVersion);if(existing?.manifest.status==='COMMITTED'&&JSON.stringify(existing)!==JSON.stringify(stored))throw new Error('INCOMPATIBLE_COMMITTED_STATE');await atomic(derivedStatePath(root,state.filename),stored);return manifest}
export async function commitDerivedState(root:string,state:DocumentState){return saveDerivedState(root,state,'COMMITTED')}
export async function markDerivedState(root:string,filename:string,status:'MISSING'|'FAILED',reason:string){await atomic(derivedStatePath(root,filename),{manifest:{schemaVersion:'1',documentFilename:filename,status,reason,createdAt:new Date().toISOString()}})}
export async function saveRevisionReceipt(root:string,filename:string,receipt:unknown){await atomic(receiptPath(root,filename),receipt)}
