import { sha256, type EntryType, type StructuralEntry, type StructuralIndex } from './types.js';
const terms=(text:string)=>[...new Set((text.toLowerCase().match(/[\p{L}\p{N}_-]{2,}/gu)??[]))];
const labels=(text:string)=>[...text.matchAll(/\\label\{([^}]+)\}/g)].map(x=>x[1]);
const tags=(text:string)=>[...text.matchAll(/\\tag\{([^}]+)\}/g)].map(x=>x[1]);
export function buildStructuralIndex(source:string):StructuralIndex {
 const chunks:{type:EntryType;start:number;end:number;path:string[];ordinal:number}[]=[]; const headings=[...source.matchAll(/^#{1,6}\s+(.+)$/gm)];
 chunks.push({type:'document',start:0,end:Buffer.byteLength(source),path:[],ordinal:0});
 headings.forEach((m,i)=>{const level=m[0].indexOf(' '); const start=m.index!; const end=i+1<headings.length?headings[i+1].index!:source.length; const path=headings.slice(0,i+1).filter(h=>h[0].indexOf(' ')<=level).map(h=>h[1].trim()); chunks.push({type:level===1?'section':level===2?'subsection':'heading',start,end,path,ordinal:i});});
 const displays=[...source.matchAll(/^\$\$\r?\n[\s\S]*?^\$\$\s*$/gm)]; displays.forEach((m,i)=>chunks.push({type:'display_equation',start:m.index!,end:m.index!+m[0].length,path:headingPath(headings,m.index!),ordinal:i}));
 const boundaries=[...source.matchAll(/(?:^|\n\n)(?!#|\$\$)([^\n][\s\S]*?)(?=\n\n|$)/g)]; boundaries.forEach((m,i)=>{const text=m[1]; const start=(m.index??0)+m[0].indexOf(text); if(!text.includes('$$')) chunks.push({type:'paragraph',start,end:start+text.length,path:headingPath(headings,start),ordinal:i});});
 const sorted=chunks.sort((a,b)=>a.start-b.start||a.end-b.end); const entries=sorted.map((c,i):StructuralEntry=>{const text=source.slice(c.start,c.end); const parent=sorted.filter(x=>x.start<=c.start&&x.end>=c.end&&x!==c).sort((a,b)=>(a.end-a.start)-(b.end-b.start))[0]; const id=`${c.type}:${sha256(`${parent?.type??'root'}:${c.ordinal}:${sha256(text)}`).slice(0,24)}`; return {entryId:id,type:c.type,startByte:Buffer.byteLength(source.slice(0,c.start)),endByte:Buffer.byteLength(source.slice(0,c.end)),textSha256:sha256(text),parentId:parent?`${parent.type}:${parent.ordinal}`:undefined,childIds:[],ordinal:c.ordinal,headingPath:c.path,labels:labels(text),tags:tags(text),lexicalTerms:terms(text),deterministicAliases:[...labels(text),...tags(text),...c.path.map(x=>x.toLowerCase())],neighboringEntryIds:[]};});
 entries.forEach((e,i)=>e.neighboringEntryIds=[entries[i-1]?.entryId,entries[i+1]?.entryId].filter(Boolean) as string[]); return {entries,byId:Object.fromEntries(entries.map(e=>[e.entryId,e]))};
}
function headingPath(headings:RegExpMatchArray[], at:number){return headings.filter(h=>(h.index??0)<=at).slice(-3).map(h=>h[1].trim());}
export function entryText(state:{documentBytes:Buffer}, entry:StructuralEntry){const text=state.documentBytes.toString('utf8'); const bytes=state.documentBytes; const value=bytes.subarray(entry.startByte,entry.endByte).toString('utf8'); if(sha256(value)!==entry.textSha256) throw new Error('STALE_INDEX_ENTRY'); return value;}
